### ISSUE TITLE
Will not compile on Windows 10 Pro 64bits

### ISSUE THREAD

**Issue by caecos** [RCameron93/FehlerFabrik#1]
4-mingw32/bin/ld.exe: C:\msys64\home\caeco\modules\fehlerfabrik/src/Rasoir.cpp:48: undefined reference to `src_delete'
collect2.exe: error: ld returned 1 exit status
make: *** [C:/msys64/Rack-SDK/compile.mk:59 : plugin.dll] Erreur 1

**Comment by RCameron93** [comment]
This is [this](https://github.com/VCVRack/Rack/issues/1792) issue. 

I've got it working on macOS fine but I haven't tried it on Windows at all. I'll mess around with it on Windows and see what combination of flags and files builds. Unfortunately my Windows machine is currently in bits, and doesn't have a dev environment set-up, so it may be a couple of days before I can properly take a look at this.

**Comment by caecos** [comment]
OK, thanks for the fast reply and I will take a look on my side…regards.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

De : Ross Cameron<mailto:notifications@github.com>
Envoyé le :mardi 21 juillet 2020 11:52
À : RCameron93/FehlerFabrik<mailto:FehlerFabrik@noreply.github.com>
Cc : caecos<mailto:caecos@hotmail.ca>; Author<mailto:author@noreply.github.com>
Objet :Re: [RCameron93/FehlerFabrik] Will not compile on Windows 10 Pro 64bits (#1)


This is this<https://github.com/VCVRack/Rack/issues/1792> issue.

I've got it working on macOS fine but I haven't tried it on Windows at all. I'll mess around with it on Windows and see what combination of flags and files builds. Unfortunately my Windows machine is currently in bits, and doesn't have a dev environment set-up, so it may be a couple of days before I can properly take a look at this.

**Comment by SteveRussell33** [comment]
I solved this locally by copying the `dep/` folder from the https://github.com/VCVRack/Fundamental repo (previously built) and using that repo's makefile as well as changing the include directive in Rasoir.cpp from https://github.com/RCameron93/FehlerFabrik/blob/7fa9e8affb0ed86ed9add7d8facc0bff8ee7bc92/src/Rasoir.cpp#L9 to: `#include "samplerate.h"`

HTH

**Comment by caecos** [comment]
Works fine...excellent solution...regards

**Comment by RCameron93** [comment]
Thanks @SteveRussell33, I've changed the makefile to essentially copy the Fundamental one and altered the include statement as well. I can build from source on my Windows machine and it all seems to be OK. I'm now however having issues with wget on my Mac, so I won't be able to confirm this version works there until I get that sorted.
