### ISSUE TITLE
It would be nice if the tooltips for the crossover were in Hz or kHz instead of arbitrary units

### ISSUE THREAD

**Issue by squinkylabs** [RCameron93/FehlerFabrik#10]
Also, it's purely a matter of style, but the pane seems awfully large on this module. It does have a lot of I/O, but still is seems large.

Very nice module!

**Comment by RCameron93** [comment]
Sorry, what module are you referring to here?

**Comment by squinkylabs** [comment]
oh, sorry! The crossover. nice module!

**Comment by RCameron93** [comment]
I've added this in [v.1.1.1](https://github.com/RCameron93/FehlerFabrik/commit/06f7e9610d86630498127ae34c16eae389c2fee0). 

In doing so I've changed the actual internal parameter scaling to an exponential function from it's original quadratic one, so the knobs will have a slightly different curve and the default centre value isn't a nice round number anymore, but it's pretty close to what it was and I'm happier with it displaying in Hz. Note that the frequency inputs _aren't_ tracking V/Oct.

The size of the panel is definitely a matter of style - the module is inspired by older style hardware units that were _very_ generous with the space between the knobs:

![](https://www.bozak.com/wp-content/uploads/1u-fronts.jpg)
![](http://www.isonoe.com/wp-content/gallery/frequency-isolator/03_isolator.jpg)

A far cry from some of the ruthlessly efficient panel layouts you can find in the modular world but something that I like, gives it a high class feel!

**Comment by squinkylabs** [comment]
cool. sounds good.
