### ISSUE TITLE
PSI OP should not have "Hardware clone" tag

### ISSUE THREAD

**Issue by AndrewBelt** [RCameron93/FehlerFabrik#11]
Is PSI OP a clone of a hardware module? The [Hardware clone tag](https://vcvrack.com/manual/Manifest#hardware-clone) is reserved for modules that "clone the functionality, panel design, and component layout of a hardware module on the market."

**Comment by RCameron93** [comment]
It did fit those requirements at one point but not any more. I've updated the tag for [v1.1.1.](https://github.com/RCameron93/FehlerFabrik/commit/1d478ec3669dcc2f167a1ece4102b27eeefab336)
