### ISSUE TITLE
Monte step probability knob tooltip percentages are incorrect

### ISSUE THREAD

**Issue by danhphotos** [RCameron93/FehlerFabrik#12]
The step probability percentage values displayed in the tooltips for the step probability knobs of Monte are incorrect. With or without a cable plugged into the associated step probability CV input jack, for example at the maximum value the tooltip says 1% but it is actually 100% probability that a trigger will be generated. For another example, at midpoint (12 o'clock) the tooltip says 0.5% but it is actually 50% probability that a trigger will be generated. It appears that all step percentage values are displayed as the actual percentage value divided by 100. Except for this minor detail this is an excellent module!

**Comment by RCameron93** [comment]
Fixed in [v.1.1.1](https://github.com/RCameron93/FehlerFabrik/commit/ed4ec14a56b5b30e32454a566769e4317f96f5d4). Glad you're enjoying it!
