### ISSUE TITLE
Random Clock: voltage

### ISSUE THREAD

**Issue by Eurikon** [RCameron93/FehlerFabrik#13]
Hi, thanks for your modules!

Could you please add a setting in the menu for the Random Clock module Luigi, that will allow for setting a higher output voltage.

As it is now the incoming 10 volt clock signal is capped at 5 volt, a choice to have it output at 10 volt would be useful.

![Screenshot 2021-02-15 at 21 34 27](https://user-images.githubusercontent.com/40998416/107991008-00adb280-6fd6-11eb-8062-ceae9264c597.png)

**Comment by RCameron93** [comment]
I started a full time job in February, and I've had literally zero time to dedicate to this project since then! That being said, this has belatedly been changed - at it's max amp setting Luigi now outputs 10v
https://github.com/RCameron93/FehlerFabrik/commit/61b5510a1540bdd1e9bd64ea4567ad4fb3c2618e
