### ISSUE TITLE
Please update to VCV v2

### ISSUE THREAD

**Issue by vcvrackideas** [RCameron93/FehlerFabrik#14]
Hi! Since beta of v2 is here could you update your cool modules to it please? Thanks!

**Comment by RCameron93** [comment]
An initial v2 version has been added with https://github.com/RCameron93/FehlerFabrik/commit/b6826bed44433e0a4f6786a8b814fa59de00e68c

A proper update will be pushed to the library when I'm done with the development of Botzinger!
