### ISSUE TITLE
Q: PSI-OP Possible to make sound identical each trigger?

### ISSUE THREAD

**Issue by docb** [RCameron93/FehlerFabrik#15]
hi,
very great module,
while playing around with making percussion sounds i recognized that the sound differs a bit on each trigger - often alternating.
this can be made transparent if e.g. a reverb is behind.
sometimes i'd like to have an identical sound, is this possible? e.g. that a "hihat" does not sound like a metronom ....
thx.

**Comment by docb** [comment]
may be this could be a similar problem as with random generators which are not seedable (e.g VCV noise causes the same thing)

**Comment by RCameron93** [comment]
I think the effect you're hearing is the same as what was raised in a prior
issue (https://github.com/RCameron93/FehlerFabrik/issues/7)

Try toggling the oscillator sync option in the right click menu and see if
it helps

**Comment by docb** [comment]
Perfect, thanks!!
