### ISSUE TITLE
Artwork license question

### ISSUE THREAD

**Issue by falkTX** [RCameron93/FehlerFabrik#17]
Just a quick question, as I don't see it mentioned anywhere.
Your project is licensed under GPL-3.0-or-later, but does that include the graphics too? Or are those supposed to be in a different license?
Thanks!

**Comment by RCameron93** [comment]
Hi, yes graphics are also licensed under GPL-3.0-or-later. I also ask in good faith that people don't use my logo to pretend to be me, or to imply my authorisation of any other works.
