### ISSUE TITLE
Psi Op feature request: add oscillator sync on trigger

### ISSUE THREAD

**Issue by glocke01** [RCameron93/FehlerFabrik#7]
you might add a right-click menu option to reset/sync the oscillators on Psi Op on receiving a trigger to allow for identical transients.

**Comment by RCameron93** [comment]
My feelings on this are similar to [your previous suggestion](https://github.com/RCameron93/FehlerFabrik/issues/6), the unpredictability is part of the intention. I've added it as an option on the development branch, and again I'm going to sit with it for a while before I think about adding it to the release.

**Comment by RCameron93** [comment]
This feature will be present in the new version so I'm closing this
