### ISSUE TITLE
Bit crusher aliases a lot

### ISSUE THREAD

**Issue by squinkylabs** [RCameron93/FehlerFabrik#9]
Is it supposed to alias like this?
![image](https://user-images.githubusercontent.com/16314838/96958525-9024d800-14b2-11eb-8401-10afe5685cd5.png)

**Comment by RCameron93** [comment]
Yeah, there's absolutely no antialiasing/filtering being done at all. It's supposed to be a very harsh sound, somewhat inspired by [this video](https://www.youtube.com/watch?v=N5WYu1k4zso) where Ed DMX talks about his custom Opal sampler.

**Comment by squinkylabs** [comment]
excellent. I'm all in favor aliasing if it's intentional. I don't know how much you have followed VCV before making your modules, but if you are new you will soon find that I am infamous for my dislike of unintentional aliasing.
